### ISSUE TITLE
Handle lock on hashstore

### ISSUE THREAD

**Issue by mitra42** [internetarchive/dweb-mirror#102]
See occasionally   
```
dweb-mirror:MirrorFS Closed yourhealthmedica00dyla/__ia_thumb.jpg size=20257 +1s
(node:18423) UnhandledPromiseRejectionWarning: OpenError: IO error: lock /.data/archiveorg/.hashStore.sha1.relfilepath/LOCK: Resource temporarily unavailable
    at /usr/local/node_modules/level-packager/node_modules/levelup/lib/levelup.js:87:23
    at /usr/local/node_modules/abstract-leveldown/abstract-leveldown.js:41:14
    at /usr/local/node_modules/level-packager/node_modules/deferred-leveldown/deferred-leveldown.js:20:21
    at /usr/local/node_modules/abstract-leveldown/abstract-leveldown.js:41:14
    at /usr/local/node_modules/abstract-leveldown/abstract-leveldown.js:41:14
(node:18423) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:18423) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
More common than you'd think but because of multiple threads writing results to hashstore. Should loop

**Comment by mitra42** [comment]
Got this via a retry
