### ISSUE TITLE
Crawl - allow crawling single files

### ISSUE THREAD

**Issue by mitra42** [internetarchive/dweb-mirror#108]
Allow specifying "crawl item/filename" to get just one file

**Comment by mitra42** [comment]
./internetarchive -c AboutBan1935/AboutBan1935.gif should be command

**Comment by mitra42** [comment]
Various issues showing up that may not be related ... 
- [ ]  From log: `SmartDict.p_fetch [ 'contenthash:/contenthash/QmP4EoXsdKQapKABnfczzSNpYRTwDUMeoPZXiD8fwXZ4t2' ]` shouldnt be happenign with dweb-objects change
- [ ]  Seeing error in log 
```
 dweb-transports Fetching https://dweb.archive.org/metadata/AboutBan1935/AboutBan1935.gif via HTTP succeeded NaN bytes +2s
  dweb-transports Uncaught error in fetch TypeError: Cannot read property 'identifier' of undefined
  dweb-transports     at DwebTransports.fetch (/Users/mitra/git/dweb-mirror/node_modules/@internetarchive/dweb-archivecontroller/ArchiveItem.js:192:66)
  dweb-transports     at prom.then (/Users/mitra/git/dweb-mirror/node_modules/@internetarchive/dweb-transports/Transports.js:226:44)
  dweb-transports     at process._tickCallback (internal/process/next_tick.js:68:7)
```
- [ ] In current test, its already crawled so should be doing ZERO p_httpfetch

**Comment by mitra42** [comment]
- [x]  From log: `SmartDict.p_fetch [ 'contenthash:/contenthash/QmP4EoXsdKQapKABnfczzSNpYRTwDUMeoPZXiD8fwXZ4t2' ]` shouldnt be happenign with dweb-objects change
dweb-objects not updated

**Comment by mitra42** [comment]
Done, will be in dweb-mirror: v0.2.31 and dweb-archivecontroller: v0.1.64
