### ISSUE TITLE
IIAB - minor failing issues.

### ISSUE THREAD

**Issue by mitra42** [internetarchive/dweb-mirror#126]
FIXED 
```
http://box.local:4244/archive/archive.html?transport=HTTP&mirror=box.local%3A4244&page=n5&item=unitednov65unit fails (see Browser console Log)
curl -Lv 'http://box.local:4244/archive/bookreader/BookReader/mmenu/dist/css/jquery.mmenu.css' gets 404 
```
Problem was that Bookreader wasn't getting linked in

**Comment by mitra42** [comment]
"loading.." appears instead of the Crawl component

**Comment by mitra42** [comment]
ipfs isnt install - install_ipfs.sh appears to call install_go.sh and then fails to get go source

**Comment by mitra42** [comment]
If cache is empty and cant reach dweb.me get an error . 
```
dweb-transports:httptools Uncaught error TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at http://192.168.0.6:4244/archive/dweb-archive-bundle.js:1:83709
    at Array.forEach (<anonymous>)
    at Function.Object.deeperAssign (http://192.168.0.6:4244/archive/dweb-archive-bundle.js:1:83690)
    at ce.stateFromInfo (http://192.168.0.6:4244/archive/dweb-archive-bundle.js:38:75228)
    at ce.displayInfo (http://192.168.0.6:4244/archive/dweb-archive-bundle.js:38:74951)
    at http://192.168.0.6:4244/archive/dweb-archive-bundle.js:38:74900
    at http://192.168.0.6:4244/archive/dweb-transports-bundle.js:47:549628
```
STR
```
mv /library/archiveorg /libary/archiveorg- 
touch /library/archiveorg 
```
Go to http://box.local:4244 or wherever server is sitting for you.
