### ISSUE TITLE
Bookreader failing

### ISSUE THREAD

**Issue by mitra42** [internetarchive/dweb-mirror#162]
http://localhost:4244/arc/archive.org/details/unitednov65unit?transport=HTTP&mirror=localhost:4244
Crashing server

**Comment by mitra42** [comment]
dweb-mirror:mirrorHttp STARTING: /BookReader/BookReaderJSIA.php?id=unitednov65unit&itemPath=%2F27%2Fitems%2Funitednov65unit&server=localhost%3A4244&format=json&subPrefix=unitednov65unit&requestUri=%2Fdetails%2Funitednov65unit +192ms
/Users/mitra/git/dweb-mirror/node_modules/@internetarchive/dweb-archivecontroller/RawBookReaderResponse.js:18
        return new this({ data: Object.assign({}, from.bookreader, {metadata: from.metadata})});
                                                       ^

TypeError: Cannot read property 'bookreader' of undefined
    at Function.fromArchiveItem (/Users/mitra/git/dweb-mirror/node_modules/@internetarchive/dweb-archivecontroller/RawBookReaderResponse.js:18:56)
    at waterfall (/Users/mitra/git/dweb-mirror/mirrorHttp.js:327:49)
    at /Users/mitra/git/dweb-mirror/node_modules/async/internal/once.js:12:16
    at next (/Users/mitra/git/dweb-mirror/node_modules/async/waterfall.js:21:29)
    at /Users/mitra/git/dweb-mirror/node_modules/async/internal/onlyOnce.js:12:16
    at /Users/mitra/git/dweb-mirror/node_modules/async/internal/once.js:12:16
    at next (/Users/mitra/git/dweb-mirror/node_modules/async/waterfall.js:21:29)
    at /Users/mitra/git/dweb-mirror/node_modules/async/internal/onlyOnce.js:12:16
    at ArchiveItem.trySave (/Users/mitra/git/dweb-mirror/ArchiveItemPatched.js:280:7)
    at nextTask (/Users/mitra/git/dweb-mirror/node_modules/async/waterfall.js:16:14)
    at next (/Users/mitra/git/dweb-mirror/node_modules/async/waterfall.js:23:9)
    at /Users/mitra/git/dweb-mirror/node_modules/async/internal/onlyOnce.js:12:16
    at tryRead.call (/Users/mitra/git/dweb-mirror/ArchiveItemPatched.js:272:9)
    at _parse (/Users/mitra/git/dweb-mirror/ArchiveItemPatched.js:229:13)
    at MirrorFS.readFile (/Users/mitra/git/dweb-mirror/ArchiveItemPatched.js:163:13)
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)

**Comment by mitra42** [comment]
- [ ] fix fragility
- [ ] why isnt from defined
- [ ] fragility: erroneously tested [link](http://localhost:4244/ /BookReader/BookReaderJSIA.php?id=unitednov65unit&itemPath=%2F27%2Fitems%2Funitednov65unit&server=localhost%3A4244&format=json&subPrefix=unitednov65unit&requestUri=%2Fdetails%2Funitednov65unit ) that also crashed it

**Comment by mitra42** [comment]
from definition 
- [x] in MH.sendBookReaderJSIA waterfall is exiting with ai=undefined, which is obviously wrong. 
BECAUSE 
- [x] failing in  ai.fetch_bookreader(req.opts, cb) 
- [x] fetch_bookreader not passings "this" when reading from net.

**Comment by mitra42** [comment]
fragility on `/ /Bookreader`
Double call to next() in app.use where handles errors, if no errors actually happened.
