### ISSUE TITLE
Pictures are not properly shown when accessed via box.local

### ISSUE THREAD

**Issue by vlnn** [internetarchive/dweb-mirror#366]
When I open https://archive.org/details/ia-25-wf I can see several pictures on the page
<img width="1210" alt="CleanShot 2022-11-18 at 00 46 37@2x" src="https://user-images.githubusercontent.com/29273499/202576402-ac72907d-e3f8-461f-97b0-d565d87f63fd.png">

but for http://box.local:4244/details/ia-25-wf I get black placeholder only:

<img width="1071" alt="CleanShot 2022-11-18 at 00 45 15@2x" src="https://user-images.githubusercontent.com/29273499/202576183-54455d50-5e85-4d40-908a-d46ac033bb70.png">

Log is attached.

```
Nov 17 17:41:42 box internetarchive[1271]: 2022-11-17T22:41:42.936Z dweb-mirror:mirrorHttp STARTING: /info
Nov 17 17:41:42 box internetarchive[1271]: GET /info - 304 - 2.815 ms
Nov 17 17:41:45 box internetarchive[1271]: 2022-11-17T22:41:45.785Z dweb-mirror:mirrorHttp STARTING: /metadata/ia-25-wf
Nov 17 17:41:45 box internetarchive[1271]: GET /metadata/ia-25-wf - 304 - 53.495 ms
Nov 17 17:41:45 box internetarchive[1271]: 2022-11-17T22:41:45.882Z dweb-mirror:mirrorHttp STARTING: /download/ia-25-wf/wf-banner-button.png
Nov 17 17:41:45 box internetarchive[1271]: 2022-11-17T22:41:45.882Z dweb-mirror:mirrorHttp Sending ArchiveFile ia-25-wf/wf-banner-button.png
Nov 17 17:41:45 box internetarchive[1271]: 2022-11-17T22:41:45.887Z dweb-transports Opening stream from https://www-dweb-cors.dev.archive.org/cors/ia-25-wf/wf-banner-button.png via HTTP
Nov 17 17:41:45 box internetarchive[1271]: 2022-11-17T22:41:45.887Z dweb-transports:httptools p_httpfetch: https://www-dweb-cors.dev.archive.org/cors/ia-25-wf/wf-banner-button.png ''
Nov 17 17:41:45 box internetarchive[1271]: 2022-11-17T22:41:45.890Z dweb-mirror:mirrorHttp STARTING: /advancedsearch.php?output=json&q=identifier%3A(opensource_image%20OR%20community)&rows=2&page=1&sort[]=identifier&fl=identifier%2Ctitle%2Ccollection%2Cmediatype%2Cdownloads%2Ccreator%2Cnum_reviews%2Cpublicdate%2Citem_count%2Cloans__status__status
Nov 17 17:41:45 box internetarchive[1271]: 2022-11-17T22:41:45.896Z dweb-transports Fetching https://www-dweb-cors.dev.archive.org/advancedsearch.php?output=json&q=identifier%3A(community)&rows=1&page=1&sort[]=identifier&fl=identifier%2Ctitle%2Ccollection%2Cmediatype%2Cdownloads%2Ccreator%2Cnum_reviews%2Cpublicdate%2Citem_count%2Cloans__status__status via HTTP
Nov 17 17:41:45 box internetarchive[1271]: 2022-11-17T22:41:45.896Z dweb-transports:httptools p_httpfetch: https://www-dweb-cors.dev.archive.org/advancedsearch.php?output=json&q=identifier%3A(community)&rows=1&page=1&sort[]=identifier&fl=identifier%2Ctitle%2Ccollection%2Cmediatype%2Cdownloads%2Ccreator%2Cnum_reviews%2Cpublicdate%2Citem_count%2Cloans__status__status ''
Nov 17 17:41:46 box internetarchive[1271]: 2022-11-17T22:41:46.490Z dweb-transports:httptools Fetch of https://www-dweb-cors.dev.archive.org/advancedsearch.php?output=json&q=identifier%3A(community)&rows=1&page=1&sort[]=identifier&fl=identifier%2Ctitle%2Ccollection%2Cmediatype%2Cdownloads%2Ccreator%2Cnum_reviews%2Cpublicdate%2Citem_count%2Cloans__status__status opened
Nov 17 17:41:46 box internetarchive[1271]: 2022-11-17T22:41:46.493Z dweb-transports Fetching https://www-dweb-cors.dev.archive.org/advancedsearch.php?output=json&q=identifier%3A(community)&rows=1&page=1&sort[]=identifier&fl=identifier%2Ctitle%2Ccollection%2Cmediatype%2Cdownloads%2Ccreator%2Cnum_reviews%2Cpublicdate%2Citem_count%2Cloans__status__status via HTTP succeeded NaN bytes
Nov 17 17:41:46 box internetarchive[1271]: 2022-11-17T22:41:46.498Z dweb-transports:httptools Fetch of https://www-dweb-cors.dev.archive.org/cors/ia-25-wf/wf-banner-button.png opened
Nov 17 17:41:46 box internetarchive[1271]: 2022-11-17T22:41:46.500Z dweb-mirror:MirrorFS ERROR: ArchiveFilePatched.cacheAndOrStream failed TypeError: readableStream.on is not a function at new ReadableStream (/opt/iiab/internetarchive/node_modules/readable-stream-clone/readableStreamClone.js:8:20) at /opt/iiab/internetarchive/node_modules/@internetarchive/dweb-mirror/MirrorFS.js:648:32 at /opt/iiab/internetarchive/node_modules/@internetarchive/dweb-mirror/MirrorFS.js:299:11 at FSReqCallback.oncomplete (node:fs:197:23)
Nov 17 17:41:46 box internetarchive[1271]: 2022-11-17T22:41:46.500Z dweb-mirror:ArchiveFile Unable to cacheOrStream ia-25-wf/wf-banner-button.png
Nov 17 17:41:46 box internetarchive[1271]: 2022-11-17T22:41:46.500Z dweb-mirror:mirrorHttp ERROR: streamArchiveFile failed for ia-25-wf/wf-banner-button.png: readableStream.on is not a function
Nov 17 17:41:46 box internetarchive[1271]: GET /download/ia-25-wf/wf-banner-button.png - 404 35 619.253 ms
Nov 17 17:41:46 box internetarchive[1271]: GET /advancedsearch.php?output=json&q=identifier%3A(opensource_image%20OR%20community)&rows=2&page=1&sort[]=identifier&fl=identifier%2Ctitle%2Ccollection%2Cmediatype%2Cdownloads%2Ccreator%2Cnum_reviews%2Cpublicdate%2Citem_count%2Cloans__status__status - 304 - 613.874 ms
Nov 17 17:42:04 box internetarchive[1271]: 2022-11-17T22:42:04.197Z dweb-transports:httptools p_httpfetch: https://dweb.me/info ''
Nov 17 17:42:04 box internetarchive[1271]: 2022-11-17T22:42:04.773Z dweb-transports:httptools Fetch of https://dweb.me/info opened
Nov 17 17:42:05 box internetarchive[1271]: 2022-11-17T22:42:05.900Z dweb-mirror:mirrorHttp STARTING: /mds/v1/get_related/all/ia-25-wf
Nov 17 17:42:05 box internetarchive[1271]: 2022-11-17T22:42:05.916Z dweb-transports Opening stream from https://be-api.us.archive.org/mds/v1/get_related/all/ia-25-wf via HTTP
Nov 17 17:42:05 box internetarchive[1271]: 2022-11-17T22:42:05.916Z dweb-transports:httptools p_httpfetch: https://be-api.us.archive.org/mds/v1/get_related/all/ia-25-wf ''
Nov 17 17:42:07 box internetarchive[1271]: 2022-11-17T22:42:07.003Z dweb-transports:httptools Fetch of https://be-api.us.archive.org/mds/v1/get_related/all/ia-25-wf opened
Nov 17 17:42:07 box internetarchive[1271]: 2022-11-17T22:42:07.006Z dweb-mirror:MirrorFS ERROR: ArchiveFilePatched.cacheAndOrStream failed TypeError: readableStream.on is not a function at new ReadableStream (/opt/iiab/internetarchive/node_modules/readable-stream-clone/readableStreamClone.js:8:20) at /opt/iiab/internetarchive/node_modules/@internetarchive/dweb-mirror/MirrorFS.js:648:32 at /opt/iiab/internetarchive/node_modules/@internetarchive/dweb-mirror/MirrorFS.js:299:11 at FSReqCallback.oncomplete (node:fs:197:23)
Nov 17 17:42:12 box internetarchive[1271]: 2022-11-17T22:42:12.951Z dweb-mirror:mirrorHttp STARTING: /info
Nov 17 17:42:12 box internetarchive[1271]: GET /info - 304 - 2.950 ms
Nov 17 17:42:34 box internetarchive[1271]: 2022-11-17T22:42:34.198Z dweb-transports:httptools p_httpfetch: https://dweb.me/info ''
Nov 17 17:42:34 box internetarchive[1271]: 2022-11-17T22:42:34.777Z dweb-transports:httptools Fetch of https://dweb.me/info opened

```

**Comment by vlnn** [comment]
This is resolved now for me -- thanks! (not sure if it's due to upgrade of my iiab software, or due to upstream fixes)
