### ISSUE TITLE
Errors at startup: readableStream.on is not a function

### ISSUE THREAD

**Issue by mitra42** [internetarchive/dweb-mirror#369]
I'm seeing errors of the form 
 ```
  dweb-mirror:MirrorFS ERROR: ArchiveFilePatched.cacheAndOrStream failed TypeError: readableStream.on is not a function at new ReadableStream (/Users/mitra/git/github_internetarchive/dweb-mirror/node_modules/readable-stream-clone/readableStreamClone.js:8:20) at /Users/mitra/git/github_internetarchive/dweb-mirror/MirrorFS.js:648:32 at /Users/mitra/git/github_internetarchive/dweb-mirror/MirrorFS.js:299:11     at FSReqCallback.oncomplete (node:fs:197:23)     at FSReqCallback.callbackTrampoline (node:internal/async_hooks:130:17) +0ms
 ```
 When I run it locally. This may be a problem with my test setup, but should track it down.

**Comment by mitra42** [comment]
This will be fixed in 0.2.91 based on DwebTransports 0.2.2 where I fixed some bitrot due to Node now include a "fetch" but with an unexpected API (using ReadableStreams).
