### ISSUE TITLE
mirrorHttp crash with ERR_HTTP_HEADERS_SENT

### ISSUE THREAD

**Issue by mitra42** [internetarchive/dweb-mirror#85]
```
  dweb-mirror:mirrorHttp STARTING: /arc/archive.org/thumbnail/survey_crawl +5ms
  dweb-mirror:mirrorHttp Sending Thumbnail for survey_crawl +1ms
TransportError: Transport Error 500: 'NoneType' object is not iterable
    at Function.p_rawfetch (/Users/brewster/tmp/git/dweb-mirror/node_modules/@internetarchive/dweb-transports/Transports.js:227:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
GET /arc/archive.org/thumbnail/archiveteam - 200 - 338.678 ms
  dweb-mirror:mirrorHttp STARTING: /ipfs/zdj7Wf6uHuL349omW6bhqkwF68BhEokTes8vWqqKorLHwueXB +51ms
  dweb-mirror:mirrorHttp FAILING: /ipfs/zdj7Wf6uHuL349omW6bhqkwF68BhEokTes8vWqqKorLHwueXB +0ms
GET /ipfs/zdj7Wf6uHuL349omW6bhqkwF68BhEokTes8vWqqKorLHwueXB - 404 193 0.507 ms
  dweb-transports Fetching https://dweb.archive.org/metadata/fav-_unlimited_watch_baby_driver_online_free_ultra4k-hd_ via HTTP succeeded NaN bytes +59ms
  dweb-mirror:mirrorHttp loadedAI: Unable to retrieve metadata for fav-_unlimited_watch_baby_driver_online_free_ultra4k-hd_ +3ms
  dweb-mirror:mirrorHttp loadedAI: Unable to retrieve metadata for fav-_unlimited_watch_baby_driver_online_free_ultra4k-hd_ +0ms
_http_outgoing.js:470
    throw new ERR_HTTP_HEADERS_SENT('set');
    ^

Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:470:11)
    at Array.write (/Users/brewster/tmp/git/dweb-mirror/node_modules/finalhandler/index.js:285:9)
    at listener (/Users/brewster/tmp/git/dweb-mirror/node_modules/on-finished/index.js:169:15)
    at onFinish (/Users/brewster/tmp/git/dweb-mirror/node_modules/on-finished/index.js:100:5)
    at callback (/Users/brewster/tmp/git/dweb-mirror/node_modules/ee-first/index.js:55:10)
    at IncomingMessage.onevent (/Users/brewster/tmp/git/dweb-mirror/node_modules/ee-first/index.js:93:5)
    at IncomingMessage.emit (events.js:182:13)
    at endReadableNT (_stream_readable.js:1094:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by mitra42** [comment]
Note two issues -
a) why failed
b) why failure crashed server

**Comment by mitra42** [comment]
REPEATABLE [http://loalhost:4244/arc/archive.org/metadata/fav-_unlimited_watch_baby_driver_online_free_ultra4k-hd_]
triggers `is_dark` error handling - but generates above stack.

**Comment by mitra42** [comment]
Was calling cb twice in _fetch_metadata on is_dark error, hard to protect against this crashing.

**Comment by mitra42** [comment]
* Fix still gives a 500 error but without crash :-(
* FIxed mirrorHttp to send 404 on all errors. 
* But that isn't really what we want ... I think we want the metadata with the is_dark with no metadata field.

**Comment by mitra42** [comment]
Fixed so gets back metadata with is_dark:true
