### ISSUE TITLE
./crawl.js --level all zandvoort.newspapers.1992.zandvoorts.nieuwsblad failing database not open

### ISSUE THREAD

**Issue by mitra42** [internetarchive/dweb-mirror#95]
[ ] Something is failing in leveldb
[ ] And the failure isnt being caught correctly

```
  dweb-mirror:MirrorFS Closed zandvoort.newspapers.1992.zandvoorts.nieuwsblad/1992.Zandvoorts.Nieuwsblad_djvu.txt size=10072519 +34s
(node:7043) UnhandledPromiseRejectionWarning: ReadError: Database is not open
    at maybeError (/Users/mitra/git/dweb-mirror/node_modules/level-packager/node_modules/levelup/lib/levelup.js:293:32)
    at LevelUP.put (/Users/mitra/git/dweb-mirror/node_modules/level-packager/node_modules/levelup/lib/levelup.js:187:7)
    at Function.f (/Users/mitra/git/dweb-mirror/HashStore.js:36:40)
    at Function.put (/Users/mitra/git/dweb-mirror/HashStore.js:28:135)
    at fs.rename (/Users/mitra/git/dweb-mirror/MirrorFS.js:279:68)
    at FSReqWrap.oncomplete (fs.js:141:20)
(node:7043) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 9)
```

**Comment by mitra42** [comment]
Not happening any more
