### ISSUE TITLE
Rachel bugs seen (might not be Rachel specific

### ISSUE THREAD

**Issue by mitra42** [internetarchive/dweb-mirror#96]
This is a meta task for (hopefully minor) issues during the Rachel default install . Some may apply to the default platform as well.  see (#93 Platform Rachel

**Comment by mitra42** [comment]
dweb-mirror:mirrorHttp STARTING: /arc/archive.org/advancedsearch?output=json&q=identifier%3A(0993_About_Bananas_01_00_41_08%20OR%20What_s_Cooking_with_Kids_-_Bananas_about_Bananas%20OR%20AboutBananasre-edit%20OR%20bananasamericanh00jenk%20OR%20bananas0000land%20OR%20bliptv-20131031-085528-Battlegeekplus-Bananas570)&rows=6&page=1&sort[]=identifier&fl=identifier%2Ctitle%2Ccollection%2Cmediatype%2Cdownloads%2Ccreator%2Cnum_reviews%2Cpublicdate%2Citem_count%2Cloans__status__status +49s
/usr/local/node_modules/@internetarchive/dweb-mirror/ArchiveMemberPatched.js:29
            cb(err);    // Not logging as not really an err for there to be no file, as will read
            ^

TypeError: cb is not a function
    at MirrorFS.readFile (/usr/local/node_modules/@internetarchive/dweb-mirror/ArchiveMemberPatched.js:29:13)
    at checkWhereValidFile (/usr/local/node_modules/@internetarchive/dweb-mirror/MirrorFS.js:111:22)
    at detect (/usr/local/node_modules/@internetarchive/dweb-mirror/MirrorFS.js:245:17)
    at /usr/local/node_modules/async/internal/createTester.js:39:17
    at /usr/local/node_modules/async/internal/once.js:12:16
    at iteratorCallback (/usr/local/node_modules/async/eachOf.js:60:13)
    at /usr/local/node_modules/async/internal/onlyOnce.js:12:16
    at /usr/local/node_modules/async/internal/createTester.js:32:21
    at waterfall (/usr/local/node_modules/@internetarchive/dweb-mirror/MirrorFS.js:239:33)
    at /usr/local/node_modules/async/internal/once.js:12:16

**Comment by mitra42** [comment]
Seeing Cannot read property 'map' of undefined on [http://192.168.0.10:4244/arc/archive.org/details/AboutBan1935?transport=HTTP&mirror=192.168.0.10:4244] - may be related to the one above

**Comment by mitra42** [comment]
dweb-mirror:mirrorHttp loadedAI: Retrieved metadata for spiritualityandreligion +1ms
  dweb-mirror:mirrorHttp loadedAI: Retrieved metadata for texts +2ms
Transports.createReadStream caught Error: URL failed to specific a scheme (before :) undefined/spiritualityandreligion
    at TransportHTTP.supports (/usr/local/node_modules/@internetarchive/dweb-mirror/node_modules/@internetarchive/dweb-transports/Transport.js:107:19)
    at _connected.filter (/usr/local/node_modules/@internetarchive/dweb-mirror/node_modules/@internetarchive/dweb-transports/Transports.js:69:60)
    at Array.filter (<anonymous>)
    at concat.urls.map.map (/usr/local/node_modules/@internetarchive/dweb-mirror/node_modules/@internetarchive/dweb-transports/Transports.js:69:43)
    at Array.map (<anonymous>)
    at Function.validFor (/usr/local/node_modules/@internetarchive/dweb-mirror/node_modules/@internetarchive/dweb-transports/Transports.js:68:22)
    at Function.p_f_createReadStream (/usr/local/node_modules/@internetarchive/dweb-mirror/node_modules/@internetarchive/dweb-transports/Transports.js:297:23)
    at Function.createReadStream (/usr/local/node_modules/@internetarchive/dweb-mirror/node_modules/@internetarchive/dweb-transports/Transports.js:336:24)
    at Function._notcached (/usr/local/node_modules/@internetarchive/dweb-mirror/MirrorFS.js:331:36)
    at checkWhereValidFile (/usr/local/node_modules/@internetarchive/dweb-mirror/MirrorFS.js:282:28)
  dweb-mirror:MirrorFS cacheAndOrStream had error reading spiritualityandreligion/__ia_thumb.jpg URL failed to specific a scheme (before :) undefined/spiritualityandreligion +44ms
  dweb-mirror:ArchiveItem Unable to cacheOrStream spiritualityandreligion/__ia_thumb.jpg +6s
  dweb-mirror:mirrorHttp item spiritualityandreligion.saveThumbnail failed: URL failed to specific a scheme (before :) undefined/spiritualityandreligion +2ms
GET /arc/archive.org/thumbnail/spiritualityandreligion - 500 1524 130.307 ms
